id = "pddl"
name = "PDDL"
version = "0.0.1"
schema_version = 1
description = "PDDL language support for Zed"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
repository = "https://github.com/arbimo/zed-pddl"

[grammars.pddl]
repository = "https://github.com/arbimo/tree-sitter-pddl"
rev = "02340847b03ce844c08638d5743e4ccd290468aa"
